// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rggjnmheqdaryfxkkqbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZ2pubWhlcWRhcnlmeGtrcWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTQxNzAsImV4cCI6MjA2MzU3MDE3MH0.zVdPNpIxhgQ7vvP53rTXuRGG5n5y6YZq4-07aELb4pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);